# Generated by Django 5.0.3 on 2024-03-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='otp',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
