# Generated by Django 5.0.3 on 2024-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticat', '0003_alter_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='vendor_application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
