# Generated by Django 5.0.3 on 2024-03-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticat', '0005_registration_otp_created_at_alter_registration_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='registering_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_no',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
